### ISSUE TITLE
Setup CI for R project

### ISSUE THREAD

**Issue by jsnel** [glotaran/TIMP#5]
As suggested for the paramGUI repository:

![image](https://user-images.githubusercontent.com/3616369/109652840-8dbd4380-7b60-11eb-857a-466051baaa78.png)

[Workflow for R here](https://github.com/actions/starter-workflows/blob/a1152703407cf97bb8e3cb39eeb909649f69fa02/ci/r.yml)

**Comment by jsnel** [comment]
Related to  https://github.com/glotaran/paramGUI/issues/19

**Comment by jsnel** [comment]
Some issues arising from package being under a subfolder and files not reachable via the expected relative paths.
The folder structure with 'www' and 'pkg' derives from the time it was primarily hosted at r-forge.

**Comment by ism200** [comment]
Beste Joris,

Hartelijk dank voor al je inspanningen op deze warme zondag !

Vanmiddag heb ik m'n tweede prik (BioNTech) gehad ...
Eva-Maria moet helaas wachten tot 17 juli (Astra)

En jullie?

Hartelijke groet,

ivo

Van: Joris Snellenburg ***@***.***>
Verzonden: zondag 13 juni 2021 17:40
Aan: glotaran/TIMP ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [glotaran/TIMP] Setup CI for R project (#5)


Closed #5<https://github.com/glotaran/TIMP/issues/5> via #6<https://github.com/glotaran/TIMP/pull/6>.

-
